spring:
server:
  port : 8081
servlet:
  contextPath: /library
#datasource:
 # driver-class-name: ${DB_DRIVER_CLASSNAME:org.h2.Driver}
  #url: ${DB_URL:jdbc:h2:./target/library}
  #username: ${DB_USERNAME:sa}
  #password: ${DB_PASSWORD:}
  #jmx-enabled: true

  #h2:
   # console:
    #  enabled: true
    #jpa:
     # hibernate:
      #  naming:
       #   implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        #  physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
